name: Weather Api GET (Every 3 Days)

on:
  schedule:
    - cron: '0 0 */3 * *'  
  workflow_dispatch:        # Allows manual triggering

jobs:
  scrape-weather:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}  # <-- Inject secret into environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests pandas python-dotenv

      - name: Run weather api
        run: python weather.py

      - name: Commit and Push updated CSV
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add weather.csv
          git commit -m "Updated weather data (3 day interval)"
          git push
